# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'FrameworkNepos' do

    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

    # Pods for FrameworkNepos

    pod 'CardIO', '~> 5.4.1'

end
